-- Добавляем поля для профиля к users
ALTER TABLE users ADD COLUMN IF NOT EXISTS passport_series VARCHAR(4);
ALTER TABLE users ADD COLUMN IF NOT EXISTS passport_number VARCHAR(6);
ALTER TABLE users ADD COLUMN IF NOT EXISTS rating DECIMAL(3,2) DEFAULT 0.00;
ALTER TABLE users ADD COLUMN IF NOT EXISTS reviews_count INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_blocked BOOLEAN DEFAULT FALSE;